# Cron file to run the conflictdetector OpenFAAS function hourly.
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: conflictdetector
  namespace: openfaas
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: openfaas-cli
            image: openfaas/faas-cli:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - -c
            - echo "verbose" | faas-cli invoke conflictdetector -g http://gateway.openfaas:8080
          restartPolicy: OnFailure
